## ActivitySim
## See full license in LICENSE.txt.

scenarioYear: 2022
# set below to 1 for everything to be internal, 0 otherwise
NO_EXTERNAL: 0

# set below to be 1 for years before 2021, 0 otherwise
PRE_COVID: 0

# convenience for expression files
HHT_NONFAMILY: [4, 5, 6, 7]
HHT_FAMILY: [1, 2, 3]

PSTUDENT_GRADE_OR_HIGH: 1
PSTUDENT_UNIVERSITY: 2
PSTUDENT_NOT: 3

GRADE_SCHOOL_MAX_AGE: 14
GRADE_SCHOOL_MIN_AGE: 5

SCHOOL_SEGMENT_NONE: 0
SCHOOL_SEGMENT_PREK: 1
SCHOOL_SEGMENT_GRADE: 2
SCHOOL_SEGMENT_HIGH: 3
SCHOOL_SEGMENT_UNIV: 4


INCOME_SEGMENT_LOW: 1
INCOME_SEGMENT_MED: 2
INCOME_SEGMENT_HIGH: 3
INCOME_SEGMENT_VERYHIGH: 4

PEMPLOY_FULL: 1
PEMPLOY_PART: 2
PEMPLOY_NOT: 3
PEMPLOY_CHILD: 4

PTYPE_FULL: 1
PTYPE_PART: 2
PTYPE_UNIVERSITY: 3
PTYPE_NONWORK: 4
PTYPE_RETIRED: 5
PTYPE_SCHOOL: 6
PTYPE_PRESCHOOL: 7

PTYPE_VALUE:
  1: PTYPE_FULL
  2: PTYPE_PART
  3: PTYPE_UNIVERSITY
  4: PTYPE_NONWORK
  5: PTYPE_RETIRED
  6: PTYPE_SCHOOL
  7: PTYPE_PRESCHOOL


CDAP_ACTIVITY_MANDATORY: M
CDAP_ACTIVITY_NONMANDATORY: N
CDAP_ACTIVITY_HOME: H

# Defines cuts on psedomsa in landuse file.  Replacement for area_type
cbd_threshold: 2
urban_threshold: 5
rural_threshold: 5

distributed_time_factor_work_mean: 1.0
distributed_time_factor_work_stddev: 0.7
distributed_time_factor_nonwork_mean: 1.0
distributed_time_factor_nonwork_stddev: 0.6
distributed_time_factor_min: 0.1
distributed_time_factor_max: 10

c_drive: 1.5

AV_OWNERSHIP_TARGET_PERCENT: 0.0
autoIVTFactorAV: 0.75
autoParkingCostFactorAV: 0.5
autoCostPerMileFactorAV: 0.7
autoTerminalTimeFactorAV: 0.65
minAgeDriveAloneAV: 13


#valueOfTime: 8.00
costPerMile: 0.325  # dollars
shortWalk: 0.333
walkSpeed: 3.00
bikeSpeed: 7.80
ebikeSpeed: 10.00
escooterSpeed: 6.70
driveSpeed: 25.00
indivTour: 1.00000

### Crosswalk between occupation and size terms
occupation_xwalk:
  1: mngt_busi_sci_health # Business, healthcare, or education -> mngt_busi_sci_health
  2: services # Food prep/hospitality/lodging/arts/media/personal care -> services
  3: nat_res_cnstr_maint # Landscaping/building maintenance/grounds cleaning/protective services -> nat_res_cnstr_maint
  4: sales_retail # Sales and retail -> sales_retail
  5: mngt_busi_sci_health # Life and physical sciences -> mngt_busi_scic_arts
  6: nat_res_cnstr_maint # Farming/environmental science/forestry -> nat_res_cnstr_maint
  7: nat_res_cnstr_maint # Construction/installations/repair occupations -> nat_res_cnstr_maint
  8: prod_trans_move # Production/transportation/material moving -> prod_trans_move
  9: prod_trans_move # Active military -> prod_trans_move
  995: missing # Missing Response -> missing
  997: missing # Other -> missing
  999: missing # no occupation -> missing

# RIDEHAIL Settings - all costs in dollars, times in minutes
Taxi_baseFare: 3.00
Taxi_costPerMile: 3.3
Taxi_costPerMinute: 0.46
Taxi_waitTime_mean:
  1: 5.5
  2: 9.5
  3: 13.3
  4: 17.3
  5: 26.5
#### [NICK] Updated all SD numbers from sandag_abm.properties. Were all 0 before
Taxi_waitTime_sd:
  1: 6.4
  2: 6.4
  3: 6.4
  4: 6.4
  5: 6.4
TNC_single_baseFare: 3.31
TNC_single_costPerMile: 0.96
TNC_single_costPerMinute: 0.33
TNC_single_costMinimum: 9.19
TNC_single_waitTime_mean:
  1: 3.0
  2: 6.3
  3: 8.4
  4: 8.5
  5: 10.3
TNC_single_waitTime_sd:
  1: 4.1
  2: 4.1
  3: 4.1
  4: 4.1
  5: 4.1
TNC_shared_baseFare: 1.66
TNC_shared_costPerMile: 0.48
TNC_shared_costPerMinute: 0.16
TNC_shared_costMinimum: 4.6
TNC_shared_IVTFactor: 1.5
TNC_shared_waitTime_mean:
  1: 5.0
  2: 8.0
  3: 11.0
  4: 15.0
  5: 15.0
TNC_shared_waitTime_sd:
  1: 4.1
  2: 4.1
  3: 4.1
  4: 4.1
  5: 4.1
min_waitTime: 0
max_waitTime: 50

# rapid bus wait time discount
WAIT_TIME_DISC: 1.0

ivt_lrt_multiplier: 0.85
ivt_brt_multiplier: 0.95
ivt_cmr_multiplier: 0.85
ivt_ltd_multiplier: 1.0
# line-haul mode constants; note commuter rail is based on CMRIVTT. Also currently hyperloop is not applied because we do not skim hyperloop IVTT
eb_equiv_asc: 10
brt_equiv_asc: -5
lrt_equiv_asc: -30
pnr_lrt_equiv_asc: -20
#
density_index_multiplier: -0.2
#    joint_sr2_ASC_no_auto: 0
#    joint_sr2_ASC_auto_deficient: 0
#    joint_sr2_ASC_auto_sufficient: 0
#    joint_drive_transit_ASC_no_auto: 0
cost_share_s2: 0.57
cost_share_s3: 0.37
vot_threshold_low: 8.81
vot_threshold_med: 18.00
max_walk_time: 60
max_bike_time: 60
max_walk_distance: 3
max_bike_distance: 12


# Micromobility constants
escooterVarCost: 0.39 # dollars
escooterFixedCost: 1.00 # dollars
escooterRentTime: 1
ebikeVarCost: 0.39 # dollars
ebikeFixedCost: 1.00 # dollars
ebikeRentTime: 1
ebikeownership: 0.008
ebikeMaxDist: 10.50
escooterMaxDist: 2.00
microAccessThreshold: 100

# cost of "average" monthly transit pass cost.  Used in transit pass ownership model.
# cost of pass divided by 2 for age < 18 and 65+.
monthly_transit_pass_cost: 100 # dollars

# year after which a vehicle (therefore its household) must have transponder
hhTR_Vehyear: 2029

# SHARED2 and SHARED3 Occupancies
OCC_SHARED2: 2.0
OCC_SHARED3: 3.33
# add TNC and Taxi Occupancies
OCC_TAXI: 1.1
OCC_TNC_SINGLE: 1.2
OCC_TNC_SHARED: 2.0

# EV Rebate constants
LowIncomeEVRebateCutoff: 3
MedIncomeEVRebateCutoff: 4
LowIncomeBEVRebate: 0
LowIncomePEVRebate: 0
MedIncomeBEVRebate: 0
MedIncomePEVRebate: 0

# dispersion parameters used for accessibility calculations
dispersion_parameter_automobile: -0.05
dispersion_parameter_transit: -0.05
dispersion_parameter_walk: -1.00
# perceived minute of in-vehicle time for every minute of out-of-vehicle time
out_of_vehicle_time_weight: 2.0


# Visum Script Constants

# Network_Prep.py & KNRConnectors_Setup.py
SCALEFACTOR: 5280

# MOVED TO NETWORK ATTRIBUTES, DIFFERENT BY MPO
#Walk_Speed: 3.0
#Connector_Vehicle_Speed: 20
#Intrazonal_Vehicle_Speed: 33.33333

# CostSkim_Setup.py
SOV_LOW_VOT: 3.39
SOV_MED_VOT: 7.49
SOV_HI_VOT:  20.51
SR2_LOW_VOT: 5.11
SR2_MED_VOT: 10.92
SR2_HI_VOT:  27.30
SR3_LOW_VOT: 7.76
SR3_MED_VOT: 16.82
SR3_HI_VOT:  44.04


# PuT_Skimming_Setup.py
  # Stop Type Constants
    # Peak
PkSTCabc: 0.1582
PkSTCd:   0.0531
PkSTCe:   0.0000
    # Off-Peak
OpSTCabc: 0.1075
OpSTCd:   0.0756
OpSTCe:   0.0000
  # Wait Time Perception Factor
    # Peak
PkWTPFabc: 0.88
PkWTPFd:   0.93
PkWTPFe:   1.00
    # Off-Peak
OpWTPFabc: 0.86
OpWTPFd:   0.94
OpWTPFe:   1.00
  # Perceieved IVTT Factors
    # Peak
PkIVPFa:    0.95
PkIVPFl:    0.88
PkIVPFr:    0.88
PkIVPFelse: 1.00
    # Off-Peak
OpIVPFa:    0.95
OpIVPFl:    0.86
OpIVPFr:    0.86
OpIVPFelse: 1.00
  # Boarding Penalties (seconds)
    # Global (added to all)
BrdPenGlb:   231.0
    # Peak
PkBrdPa:     372.0
PkBrdPe:     372.0
PkBrdPl:     000.0
PkBrdPr:     000.0
PkBrdPelse:  439.8
    # Off-Peak
OpBrdPa:     166.8
OpBrdPe:     166.8
OpBrdPl:     000.0
OpBrdPr:     000.0
OpBrdPelse:  540.6
  # Calculate TTF (Transit Run Time)
    # Vehicle Time Multipliers
ft1:  1.15
ft2:  1.20
ft3:  1.00
ft4:  1.09
ft11: 1.15
ft12: 1.30
ft13: 1.00
ft14: 1.09
ft21: 1.05
ft22: 1.03
  # Runtime Function
DefaultTransitSpeed: 30 #mph

# PuTSkim_PostProcessing.py
  # Walk Constants
Max_Walk_Time: 20
Max_Walk_Distance: 1
  # Vehicle Type Constants
    # Peak
PkVTCa: 0.0557
PkVTCe: 0.0000
PkVTCl: 0.1858
PkVTCr: 0.1858
    # Off-Peak
OpVTCa: 0.0432
OpVTCe: 0.0984
OpVTCl: 0.1442
OpVTCr: 0.1442

# model region constants
KNR_available: True  # SKATS does not have KNR, so set to False in configs_skats/constants.yaml
model_region_name: "Metro"
MSA_POP: 2500000  # used in vehicle type choice model
